Домашнее задание 1
Minrael/2018-FS-11-Frontend-Kerechanina pull request #1
Opened 2018-10-12 23:35 UTC by Minrael

Образец

2018-10-15 19:42 UTC, Minrael commented
1

2018-10-15 20:05 UTC, martinkomitsky commented on dist/main.js
> -!function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||O
Почему этот файл еще не удален и не в гит игноре? Сколько раз мне еще делать это замечание(((

2018-10-15 20:07 UTC, martinkomitsky requested changes
Исправить замечания, +:
1. Выполнить пункт дз про линтер, а именно, подключить его
2. Подключить конфиг для eslint от airbnb
3. В package.json написать скрипт, который его запускает
4. Запустить и исправить все ошибки, которые указаны им

2018-10-16 20:54 UTC, martinkomitsky requested changes
1. Линтер подключила, а не использовала. Создать в package.json скрипт запуска линтера с указанием пути ./src/
2. Запустить линтер, исправить все указанные им ошибки
3. Удалить мусор .index.html.swp

2018-10-17 19:10 UTC, martinkomitsky approved these changes
Проверяю этот пуллреквест в последний раз.
![image](https://user-images.githubusercontent.com/14847018/47110092-9c895100-d258-11e8-8109-4912862c13a4.png)
1. [Webpack.config.js](https://github.com/Minrael/2018-FS-11-Frontend-Kerechanina/blob/homework/dist/webpack.config.js), почему-то, находится в папке `/dist`. Он не должен там находиться, так как папка `dist` (с англ. `Distribution`) предначначена только для сборок. Нужно вынести конфиг в /.
2. В репозитории все до сих пор (!!!) присутствуют папки `/node_modules` и `/dist`. Нужно их удалить: `rm -rf {node_modules,dist}`.
3. Ошибки линтера не исправлены:
![image](https://user-images.githubusercontent.com/14847018/47110433-77491280-d259-11e8-9f0a-55f978ef6733.png)

2018-10-17 19:12 UTC, merged

2018-10-17 19:13 UTC, martinkomitsky commented
Задание смержил, потому что прошло уже много времени и ДЗ было сдано после срока. Все еще есть замечания, которые отмечал уже несколько раз.
3.